logger:
  enable: true
  level: info
  format: compact
  # filters:
  #   - sea_orm_migration=error
server:
  port: 3000
  host: http://localhost
  middlewares:
    limit_payload:
      enable: true
      body_limit: 5mb
    logger:
      enable: true
    catch_panic:
      enable: true
workers:
  mode: BackgroundQueue
mailer:
  smtp:
    enable: true
    host: localhost
    port: 1025
    secure: false
    # auth:
    #   user:
    #   password:
auth:
  secret: PqRwLF2rhHe8J22oBeHy
  expiration: 604800
