[workspace]
#

[package]
name = "loco-cli"
version = "0.1.3"
edition = "2021"
description = "loco cli website generator"
license = "Apache-2.0"
homepage = "https://docs.rs/loco-cli"
documentation = "https://docs.rs/loco-cli"
authors = ["Dotan Nahum <dotan@rng0.io>", "Elad Kaplan <kaplan.elad@gmail.com>"]

[lib]
name = "loco_cli"
path = "src/lib.rs"

[[bin]]
name = "loco"
path = "src/bin/main.rs"
required-features = []

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
cargo-generate = { version = "0.18.5", default-features = false }
eyre = "0.6.9"
rand = "0.8.5"
dialoguer = "~0.11"
regex = "1.10.2"


[dev-dependencies]
trycmd = "0.14.19"
