[package]
name = "rustyrails"
version = "0.1.0"
edition = "2021"
description = "Work in progress"
license = "Apache-2.0"
homepage = "https://docs.rs/rustyrails"
documentation = "https://docs.rs/rustyrails"
authors = ["Dotan Nahum <dotan@rng0.io>", "Elad Kaplan <kaplan.elad@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auth", "cli"]

auth = ["dep:jsonwebtoken", "dep:bcrypt"]
cli = ["dep:clap"]
testing = ["dep:axum-test"]

[dependencies]

eyre = "0.6.9"

# cli
clap = { version = "4.4.7", features = ["derive"], optional = true }

sea-orm = { version = "0.12.4", features = [
  "sqlx-postgres",        # `DATABASE_DRIVER` feature
  "sqlx-sqlite",
  "sqlx-mysql",
  "runtime-tokio-rustls",
  "macros",
] }
tokio = { version = "1.33.0", features = ["full"] }
# the rest
sqlx = "0.7.2"

serde = "1.0.193"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
serde_variant = "0.1.2"

# worker fwk 
rusty-sidekiq = { version = "0.8.1" }
async-trait = "0.1.74"
bb8 = "0.8.1"

axum = "0.6.20"
regex = "1.10.2"
lazy_static = "1.4.0"
# mailer
tera = "1.19.1"
lettre = { version = "0.11.1", default-features = false, features = [
  "builder",
  "hostname",
  "smtp-transport",
  "tokio1-rustls-tls",
] }
include_dir = "0.7.3"
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }


# cli/migrations
duct = "0.13.6"

# _meta.rs: schema discovery for truncate
# sea-schema = { version = "*", features = ["runtime-tokio-rustls", "sqlx-all"] }
# sqlx = { version = "0.7.2", default-features = false, features = [
#   "mysql",
#   "postgres",
# ] }
# url = "*"

config = "0.13.3"
tower-http = { version = "0.4.4", features = ["trace", "catch-panic"] }
tower-request-id = "0.2.1"
byte-unit = "4.0.19"

jsonwebtoken = { version = "9.1.0", optional = true }
bcrypt = { version = "0.15.0", optional = true }
validator = { version = "0.16.1", features = ["derive"] }

axum-test = { version = "13.2.0", optional = true }

# gen 
rrgen = "0.5.0"
chrono = "0.4.31"

[dependencies.sea-orm-migration]
version = "0.12.4"
features = [
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  "runtime-tokio-rustls", # `ASYNC_RUNTIME` feature
  "sqlx-postgres",        # `DATABASE_DRIVER` feature
  "sqlx-sqlite",
  "sqlx-mysql",
]


[patch.crates-io]
# see https://github.com/heim-rs/darwin-libproc/pull/9
# rusty-sidekiq needs robotty/simple-process-stats which depends on darwin-libproc, which depends on
# a too old memchr version which sqlx needs. because libproc is native and not pure rust,
# cargo cannot resolve it. so we patch the libproc dependency.
# since simple_process_stats use by rusty-sidekiq is minimal, its better to replace it with something
# that has more velocity on updating dependencies.
darwin-libproc = { git = "https://github.com/codota/darwin-libproc" }

[dev-dependencies]
rstest = "0.18.2"
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
