blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/rustyrails-rs/rustyrails/discussions
    about: Please ask questions or raise indefinite concerns on Discussions
