[package]
name = "loco-extras"
version = "0.1.0"
description = "Loco extras contains a list of common implementation that are generally useful when working with loco.rs"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
loco-rs = { path = "../", default-features = false }
async-trait = { workspace = true }
axum = { workspace = true }

# initializer
axum-prometheus = { version = "0.6.1", optional = true }

[features]
default = []
full = ["initializer-prometheus"]

initializer-prometheus = ["dep:axum-prometheus"]
